prclin/alumni-circle

model/response/base.go
=> feat: uniform response

util/md5.go
=> feat:添加MD5工具函数

controller/account.go, dao/account.go, model/entity/account.go, model/po/account.go, model/response/base.go, service/account.go, service/auth.go, util/digest.go
=> feat: finish get current account info

controller/account.go, dao/account.go, model/po/account.go, service/account.go, util/common.go
=> feat: finish put account info

controller/account.go, dao/image.go, model/entity/image.go, model/po/image.go, service/account.go
=> feat: finish get photo wall

controller/account.go, core/gorm.go, dao/image.go, model/po/image.go, service/account.go
=> feat: finish put photo wall

controller/tag.go, dao/tag.go, model/po/tag.go, service/tag.go
=> feat: finish post tag

controller/tag.go, dao/tag.go, model/po/tag.go, service/tag.go
=> feat: finish put tag

controller/tag.go, dao/tag.go, model/po/tag.go, service/tag.go
=> refactor and feat

controller/tag.go, dao/tag.go, model/request/request.go, service/tag.go
=> feat: finish get tag list

controller/account.go, dao/tag.go, model/tag.go, service/account.go
=> feat: finish put account tag

controller/account.go, dao/tag.go, service/account.go
=> feat: finish get account tag

application.yaml, config/configuration.go, config/oss.go, controller/file.go, core/core.go, core/oss.go, dao/image.go, global/global.go, go.mod, go.sum, model/image.go, service/oss.go
=> feat: finish post image

controller/break.go, dao/break.go, dao/image.go, dao/topic.go, model/break.go, model/image.go, model/topic.go, service/break.go
=> feat: finish post break

controller/topic.go, dao/topic.go, service/break.go, service/topic.go
=> feat: finish post topic

controller/break.go, dao/break.go, service/break.go
=> feat: put break

controller/break.go, dao/break.go, service/break.go
=> feat: finish delete break

controller/auth.go, dao/api.go, model/api.go, service/auth.go
=> feat: finish post api

controller/auth.go, dao/api.go, service/auth.go
=> feat: finish put api

controller/auth.go, dao/api.go, service/auth.go
=> feat: finish delete api

controller/auth.go, dao/api.go, model/api.go, service/auth.go
=> feat: finish get api list

controller/auth.go, dao/role.go, service/auth.go
=> feat: finish put role

controller/auth.go, dao/role.go, service/auth.go
=> feat: finish delete role

controller/auth.go, dao/api.go, dao/image.go, dao/role.go, model/api.go, service/auth.go
=> feat: finish post api allocation

controller/auth.go, dao/api.go, service/auth.go
=> feat: finish delete api allocation

controller/auth.go, dao/account.go, dao/role.go, service/auth.go
=> feat: finish post role allocation

controller/auth.go, dao/api.go, dao/role.go, service/auth.go
=> feat: finish delete role allocation

controller/account.go, dao/account.go, model/account.go, service/account.go
=> feat: finish post follow

controller/account.go, dao/account.go, service/account.go
=> feat: finish delete follow

application.yaml, config/configuration.go, config/mbti.go, controller/mbti.go, dao/account.go, go.mod, go.sum, model/account.go, model/mbti.go, service/mbti.go
=> feat: finish get mbti question sheet and post question sheet answer
